const animeList = [
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/21/One_Piece',
        name: 'One Piece',
        tags: ['Action', 'Fantasy', 'Adventure', 'Comedy', 'Drama'],
        quote: {
            content: 'If I die here, then I\'m a man that could only make it this far.',
            author: 'Zoro Roronoa'
        }
    },
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/1735/Naruto__Shippuuden',
        name: 'Naruto',
        tags: ['Action', 'Comedy', 'Supernatural'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/223/Dragon_Ball',
        name: 'Dragon Ball',
        tags: ['Action', 'Fantasy', 'Comedy', 'Martial Art', 'Supernatural', 'Adventure', 'Science Fiction'],
    },
    {
        level: 'S',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/235/Detective_Conan?cat=anime',
        name: 'Conan',
        tags: ['Detective', 'Comedy', 'Psychological'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/6702/Fairy_Tail',
        name: 'Fairy Tail',
        tags: ['Action', 'Fantasy', 'Adventure', 'Ecchi'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/550/Yu%E2%98%86Gi%E2%98%86Oh',
        name: 'Yu Gi Oh',
        tags: ['Adventure', 'Psychological', 'Supernatural', 'Game', 'Comedy'],
        quote: {
            content: 'Sometimes The End Of One Adventure Is Just The Beginning Of Another.',
            author: 'Yami Yuugi'
        }
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/527/Pokemon',
        name: 'Pokemon series',
        tags: ['Adventure', 'Psychological', 'Supernatural', 'Fantasy', 'Comedy'],
    },
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/5680/KOn',
        name: 'K ON!',
        tags: ['Slice of Life', 'Comendy', 'School', 'Music'],
        quote: {
            content: 'To the me back then, you don\'t need to worry. You\'ll soon find something you can do, something you can set your heart on.',
            author: 'Yui Hirasawa'
        }
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/12189/Hyouka',
        name: 'Hyouka',
        tags: ['Slice of Life', 'Comendy', 'School', 'Detective'],
    },
    {
        level: 'S+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood',
        name: 'Fullmetal Alchemist',
        tags: ['Action', 'Psychological', 'Fantasy', 'Supernatural', 'Drama', 'Martial Art', 'Adventure', 'Military'],
        quote: {
            content: 'Nothing\'s perfect, the world\'s not perfect, but it\'s there for us, trying the best it can. That\'s what makes it so damn beautiful.',
            author: 'Roy Mustang'
        }
    },
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/269/Bleach',
        name: 'Bleach',
        tags: ['Action', 'Supernatural', 'Comedy', 'Adventure'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/13759/Sakurasou_no_Pet_na_Kanojo',
        name: 'Sakurasou no Pet na Kanojo',
        tags: ['Slice of Life', 'School', 'Romance', 'Harem', 'Comedy'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33948/Hinako_Note',
        name: 'Hinako Note',
        tags: ['Slice of Life', 'Comedy'],
    },
    {
        level: 'S-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/16592/Danganronpa__Kibou_no_Gakuen_to_Zetsubou_no_Koukousei_The_Animation',
        name: 'Danganronpa Kibou No Gakuen To Zetsubou No Koukousei The Animation',
        tags: ['Action', 'Drama', 'Psychological', 'Detective', 'Supernatural'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/37993/Watashi_ni_Tenshi_ga_Maiorita/',
        name: 'Watashi ni Tenshi ga Maiorita!',
        tags: ['Slice of Life', 'Comendy', 'School'],
    },
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/918/Gintama',
        name: 'Gintama',
        tags: ['Comedy', 'Action', 'Fantasy', 'Supernatural', 'Historical', 'Martial Art'],
        quote: {
            content: 'It\'s quite easy for humans to become adults, but to always have a child-like heart that makes everything joyful isn\'t such an easy task.',
            author: 'Hattori Zenzou'
        }
    },
    {
        level: 'A-',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/11757/Sword_Art_Online',
        name: 'Sword Art Online',
        tags: ['Game', 'Action', 'fantasy', 'Adventure', 'Harem', 'Romance'],
    },
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/11061/Hunter_x_Hunter_2011',
        name: 'Hunter X Hunter',
        tags: ['Fantasy', 'Adventure', 'Action', 'Martial Art', 'Supernatural'],
        quote: {
            content: 'When I Say It Doesn\'t Hurt Me, That Means I Can Bear It.',
            author: 'Killua'
        }
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31240/Re_Zero_kara_Hajimeru_Isekai_Seikatsu?suggestion=',
        name: 'Re:Zero Kara Hajimeru Isekai Seikatsu',
        tags: ['Fantasy', 'Drama', 'Comedy', 'Action', 'Isekai', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/36510/Ulysses__Jehanne_Darc_to_Renkin_no_Kishi',
        name: 'Ulysses: Jehanne Darc to Renkin no Kishi',
        tags: ['Fantasy', 'Action'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/32105/Sousei_no_Onmyouji',
        name: 'Sousei no Onmyouji',
        tags: ['Fantasy', 'Action', 'Supernatural', 'Romance', 'Comedy'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/34420/Isekai_Izakaya__Koto_Aitheria_no_Izakaya_Nobu',
        name: 'Isekai Izakaya: Koto Aitheria no Izakaya Nobu',
        tags: ['Slice of Life', 'Food'],
    },
    {
        level: 'S+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/14719/JoJo_no_Kimyou_na_Bouken_TV?cat=anime',
        name: 'JoJo',
        tags: ['Action', 'Adventure', 'Comedy', 'Supernatural'],
        quote: {
            content: 'Muda Muda Muda Muda Muda Muda Muda Muda Muda',
            author: 'Giorno Giovanna'
        }
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/4224/Toradora',
        name: 'Toradora',
        tags: ['Comedy', 'Romance', 'School'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/1520/Black_Jack',
        name: 'Black Jack',
        tags: ['Psychological', 'Historical'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/35756/Comic_Girls',
        name: 'Comic Girls',
        tags: ['Slice of Life', 'Comedy'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/13601/PsychoPass',
        name: 'Psycho Pass',
        tags: ['Action', 'Psychological', 'Detective', 'Science Fiction'],
        quote: {
            content: 'The opposite of boredom is not pleasure… but excitement. People will gladly seek out any kind of excitement, even pain.',
            author: 'Shogo Makishima'
        }
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/24439/Kekkai_Sensen',
        name: 'Kekkai Sensen',
        tags: ['Action', 'Supernatural', 'Comedy', 'Detective', 'Fantasy'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/37141/Hataraku_Saibou_TV',
        name: 'Hataraku Saibou',
        tags: ['Comedy', 'Action'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33489/Little_Witch_Academia_TV',
        name: 'Little Witch Academia',
        tags: ['Comedy', 'School', 'Fantasy'],
    },
    {
        level: 'A+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/32093/Tanakakun_wa_Itsumo_Kedaruge',
        name: 'Tanaka Kun Wa Itsumo Kedaruge',
        tags: ['Slice of Life', 'Comedy', 'School'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/32542/Sakamoto_Desu_ga',
        name: 'Sakamoto Desu Ga',
        tags: ['Comedy', 'School'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/30831/Kono_Subarashii_Sekai_ni_Shukufuku_wo',
        name: 'Kono Subarashii Sekai ni Shukufuku wo',
        tags: ['Comedy', 'Action', 'Isekai', 'Fantasy'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/30123/Akagami_no_Shirayukihime',
        name: 'Akagami no Shirayukihime',
        tags: ['Romance', 'Psychological', 'historical', 'Otome'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/30276/One_Punch_Man',
        name: 'One Punch Man',
        tags: ['Comedy', 'Action', 'Supernatural'],
    },
    {
        level: 'S+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/2966/Ookami_to_Koushinryou',
        name: 'Ookami to Koushinryou',
        tags: ['Comedy', 'Adventure', 'Psychological', 'Romance', 'Historical', 'Supernatural', 'Action'],
        quote: {
            content: 'When a person lies, what is important is not the lie itself. No, it is their reason. Their why.',
            author: 'Horo'
        }
    },
    {
        level: 'S-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31478/Bungou_Stray_Dogs',
        name: 'Bungou Stray Dogs',
        tags: ['Action', 'Supernatural', 'Comedy'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/37430/Tensei_shitara_Slime_Datta_Ken',
        name: 'Tensei shitara Slime Datta Ken',
        tags: ['Fantasy', 'Comedy', 'Action', 'Isekai', 'Adventure'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/38481/Toaru_Kagaku_no_Railgun_T',
        name: 'To Aru Kagaku No Railgun',
        tags: ['Action', 'Comedy', 'Romance', 'Supernatural'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/18897/Nisekoi',
        name: 'Nisekoi',
        tags: ['Comedy', 'School', 'Harem', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31953/New_Game',
        name: 'New Game',
        tags: ['Slice of Life', 'Comedy', 'Game'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/29803/Overlord',
        name: 'Overlord',
        tags: ['Game', 'Fantasy', 'Action', 'Comedy', 'Isekai', 'Adventure'],
    },
    {
        level: 'S',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/1575/Code_Geass__Hangyaku_no_Lelouch',
        name: 'Code Geass',
        tags: ['Drama', 'Action', 'Mecha', 'Fantasy', 'Military'],
        quote: {
            content: 'In this world, evil can arise from the best of intentions. And there is good which can come from evil intentions.',
            author: 'C.C.'
        }
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/38759/Sewayaki_Kitsune_no_Senkosan',
        name: 'Sewayaki Kitsune No Senko San',
        tags: ['Comedy', 'Slice of Life', 'Supernatural'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/36475/Sword_Art_Online_Alternative__Gun_Gale_Online',
        name: 'Gun Gale Online',
        tags: ['Game', 'Action'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33255/Saiki_Kusuo_no_%CE%A8nan',
        name: 'Saiki Kusuo no Ψ Nan',
        tags: ['Comedy', 'School', 'Supernatural'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/28423/Kyoukai_no_Rinne_TV',
        name: 'Kyoukai no Rinne',
        tags: ['Comedy', 'Romance', 'Supernatural'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/1535/Death_Note',
        name: 'Death Note',
        tags: ['Supernatural', 'Psychological', 'Detectve', 'Horror'],
        quote: {
            content: 'There is no heaven or hell. No matter what you do while you’re alive, everybody goes to the same place once you die. Death is Equal.',
            author: 'L Lawliet'
        }
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/22101/Soredemo_Sekai_wa_Utsukushii',
        name: 'Soredemo Sekai Wa Utsukushii',
        tags: ['Fantasy', 'Adventure', 'Romance', 'Otome'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/34501/Kenka_Banchou_Otome__Girl_Beats_Boys',
        name: 'Kenka Banchou Otome: Girl Beats Boys',
        tags: ['Action', 'School', 'Otome'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/32615/Youjo_Senki',
        name: 'Youjo Senki',
        tags: ['Action', 'Isekai', 'Adventure', 'Military'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/12291/Acchi_Kocchi',
        name: 'Acchi Kocchi',
        tags: ['Slice of Life', 'School', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/249/InuYasha',
        name: 'Inuyasha',
        tags: ['Comedy', 'Action', 'Adventure', 'Supernatural', 'Romance', 'Otome'],
    },
    {
        level: 'B+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/18153/Kyoukai_no_Kanata',
        name: 'Kyoukai no Kanata',
        tags: ['Slice of Life', 'Fantasy', 'School', 'Supernatural'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/4081/Natsume_Yuujinchou',
        name: 'Natsume Yuujinchou',
        tags: ['Slice of Life', 'Supernatural'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/16498/Shingeki_no_Kyojin',
        name: 'Shingeki no Kyojin',
        tags: ['Action', 'Psychological', 'Fantasy', 'Horror'],
        quote: {
            content: 'I don\'t have time to worry if it\'s right or wrong, you can\'t hope for a horror story with a happy ending.',
            author: 'Eren Jaeger'
        }
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/38691/Dr_Stone',
        name: 'Dr. Stone',
        tags: ['Comedy', 'Action', 'Adventure', 'Supernatural'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/38000/Kimetsu_no_Yaiba',
        name: 'Kimetsu No Yaiba',
        tags: ['Action', 'Fantasy', 'Supernatural', 'Historical'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/32182/Mob_Psycho_100',
        name: 'Mob Psycho 100',
        tags: ['Action', 'Comedy', 'School', 'Supernatural', 'Psychological'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/37982/Domestic_na_Kanojo',
        name: 'Domestic na Kanojo',
        tags: ['Drama', 'School', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/36882/Arifureta_Shokugyou_de_Sekai_Saikyou',
        name: 'Arifureta Shokugyou de Sekai Saikyou',
        tags: ['Fanasy', 'Action', 'Harem', 'Isekai', 'Adventure'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/40221/Kami_no_Tou',
        name: 'Kami no Tou',
        tags: ['Drama', 'Fanasy', 'Action', 'Adventure'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/39547/Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru_Kan',
        name: 'Yahari Ore no Seishun Love Comedy wa Machigatteiru',
        tags: ['Comedy', 'School', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/39710/Yesterday_wo_Utatte',
        name: 'Yesterday wo Utatte',
        tags: ['Drama', 'Slice of Life', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/39292/Princess_Connect_Re_Dive',
        name: 'Princess Connect! Re:Dive',
        tags: ['Drama', 'Ecchi', 'Comedy', 'Action', 'Harem', 'Adventure', 'Romance', 'Fantasy'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/37349/Goblin_Slayer',
        name: 'Goblin Slayer',
        tags: ['Fantasy', 'Action', 'Horror', 'Adventure'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35790/Tate_no_Yuusha_no_Nariagari',
        name: 'Tate no Yuusha no Nariagari',
        tags: ['Drama', 'Fantasy', 'Action', 'Adventure', 'Isekai'],
    },
    {
        level: 'B+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/37447/Karakuri_Circus_TV',
        name: 'Karakuri Circus',
        tags: ['Drama', 'Action', 'Adventure'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/22199/Akame_ga_Kill',
        name: 'Akame Ga Kill',
        tags: ['Action', 'Fantasy', 'Psychological'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31442/Musaigen_no_Phantom_World',
        name: 'Musaigen no Phantom World',
        tags: ['Comedy', 'Action', 'Supernatural'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/34934/Koi_to_Uso',
        name: 'Koi to Uso',
        tags: ['Drama', 'School', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/28623/Koutetsujou_no_Kabaneri',
        name: 'Koutetsujou no Kabaneri',
        tags: ['Action', 'Horror', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/6574/Hanamaru_Youchien',
        name: 'Hanamaru Youchien',
        tags: ['Slice of Life', 'Comendy', 'School'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/19383/Yami_Shibai',
        name: 'Yami Shibai',
        tags: ['Horror', 'Supernatural', 'Psychological'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/9253/Steins_Gate',
        name: 'Steins Gate',
        tags: ['Detective', 'Science Fiction', 'Psychological', 'Romance'],
        quote: {
            content: 'Living should mean no do-overs, this is for the best.',
            author: 'Rintaro Okabe'
        }
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/1606/Kekkaishi_TV',
        name: 'Kekkaishi',
        tags: ['Comedy', 'Action', 'Adventure', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33012/Island',
        name: 'Island',
        tags: ['Slice of Life', 'Comendy', 'Romance', 'Psychological', 'Science Fiction'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/38992/Rikei_ga_Koi_ni_Ochita_no_de_Shoumei_shitemita',
        name: 'Rikei ga Koi ni Ochita no de Shoumei shitemita',
        tags: ['Comedy', 'Romance', 'Slice of Life'],
    },
    {
        level: 'A+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/35247/Owarimonogatari_2nd_Season',
        name: 'Monogatari series',
        tags: ['Harem', 'Supernatural'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/30015/ReLIFE',
        name: 'ReLIFE',
        tags: ['Slice of Life', 'School', 'Romance'],
    },
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/34798/Yuru_Camp%E2%96%B3',
        name: 'Yuru Camp',
        tags: ['Slice of Life', 'Comedy', 'Sport'],
        quote: {
            content: 'Nothing went right... I didn\'t get the time to read. My butt hurts. I guess I\'ll just have to call it curry soup.',
            author: 'Rin Shima'
        }
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35062/Mahoutsukai_no_Yome',
        name: 'Mahoutsukai no Yome',
        tags: ['Slice of Life', 'Supernatural', 'Romance'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/35860/Karakai_Jouzu_no_Takagisan',
        name: 'Karakai Jouzu no Takagi san',
        tags: ['Slice of Life', 'Comedy', 'Romance'],
    },
    {
        level: 'S',
        imgP: 'bottom',
        link: 'https://myanimelist.net/manga/70345/Grand_Blue',
        name: 'Grand Blue',
        tags: ['Slice of Life', 'Comedy', 'Sport'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33352/Violet_Evergarden',
        name: 'Violet Evergarden',
        tags: ['Psychological', 'Slice of Life'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/37450/Seishun_Buta_Yarou_wa_Bunny_Girl_Senpai_no_Yume_wo_Minai',
        name: 'Seishun Buta Yarou wa Bunny Girl Senpai no Yume wo Minai',
        tags: ['Comedy', 'School', 'Supernatural', 'Romance', 'Psychological', 'Military'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/21273/Gochuumon_wa_Usagi_Desu_ka',
        name: 'Gochuumon wa Usagi Desu ka?',
        tags: ['Comedy', 'Slice of Life'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/18671/Chuunibyou_demo_Koi_ga_Shitai_Ren/episode',
        name: 'Chuunibyou demo Koi ga Shitai!',
        tags: ['Comedy', 'School', 'Romance'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/34902/Tsurezure_Children',
        name: 'Tsurezure Children',
        tags: ['Comedy', 'School', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/28999/Charlotte',
        name: 'Charlotte',
        tags: ['Supernatural', 'Comedy', 'Psychological', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/23755/Nanatsu_no_Taizai',
        name: 'Nanatsu no Taizai',
        tags: ['Fantasy', 'Action', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33487/Masamunekun_no_Revenge',
        name: 'Masamune kun no Revenge',
        tags: ['Comedy', 'Harem', 'School', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/18095/Nourin',
        name: 'Nourin',
        tags: ['Comedy', 'School', 'Psychological'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/15583/Date_A_Live',
        name: 'Date A Live',
        tags: ['Comedy', 'Action', 'Harem', 'Supernatural', 'Romance', 'Science Fiction'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/3455/To_LOVE-Ru',
        name: 'To LOVE Ru',
        tags: ['Ecchi', 'Comedy', 'Harem', 'School', 'Fantasy'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/34262/Oushitsu_Kyoushi_Heine',
        name: 'Oushitsu Kyoushi Haine',
        tags: ['Comedy', 'Historical'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/20507/Noragami',
        name: 'Noragami',
        tags: ['Comedy', 'Action', 'Fantasy', 'Otome'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/34933/Kakegurui',
        name: 'Kakegurui',
        tags: ['Drama', 'Psychological', 'Game', 'School'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/34572/Black_Clover',
        name: 'Black Clover',
        tags: ['Fantasy', 'Action', 'Comedy', 'Adventure'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35994/Satsuriku_no_Tenshi',
        name: 'Satsuriku no Tenshi',
        tags: ['Psychological', 'Horror'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/28677/Yamadakun_to_7nin_no_Majo_TV',
        name: 'Yamada kun to 7 nin no Majo',
        tags: ['Comedy', 'Harem', 'Supernatural', 'Romance'],
    },
    {
        level: 'S-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/24833/Ansatsu_Kyoushitsu',
        name: 'Ansatsu Kyoushitsu',
        tags: ['Comedy', 'Action', 'School'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/19815/No_Game_No_Life',
        name: 'No Game No Life',
        tags: ['Game', 'Fantasy', 'Isekai', 'Supernatural', 'Drama', 'Romance', 'Comedy'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/22319/Tokyo_Ghoul',
        name: 'Tokyo Ghoul',
        tags: ['Action', 'Horror', 'Psychological', 'Fantasy'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31229/Servamp',
        name: 'Servamp',
        tags: ['Action', 'Comedy', 'Drama', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/34618/Blend_S',
        name: 'Blend S',
        tags: ['Comedy', 'Slice of Life'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/27775/Plastic_Memories',
        name: 'Plastic Memories',
        tags: ['Psychological', 'Science Fiction', 'Romance', 'Mecha'],
        quote: {
            content: 'Sometimes it takes a little bit of sadness to know what happiness is.',
            author: 'Isla'
        }
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/33506/Ao_no_Exorcist__Kyoto_Fujououhen',
        name: 'Ao no Exorcist: Kyoto Fujouou hen',
        tags: ['Action', 'Fantasy', 'Supernatural', 'Adventure', 'Comedy'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/37033/Emiyasan_Chi_no_Kyou_no_Gohan',
        name: 'Emiya san Chi no Kyou no Gohan',
        tags: ['Comedy', 'Slice of Life', 'Food'],
    },
    {
        level: 'S',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/10087/Fate_Zero',
        name: 'Fate serires',
        tags: ['Action', 'Fantasy', 'Psychological', 'Supernatural', 'Historical', 'Martial Art', 'Adventure', 'Drama'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/35849/Darling_in_the_FranXX',
        name: 'Darling in the FranXX',
        tags: ['Action', 'Mecha', 'Fantasy', 'Romance', 'Adventure', 'Science Fiction'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/37521/Vinland_Saga',
        name: 'Vinland Saga',
        tags: ['Action', 'Historical', 'Adventure'],
        quote: {
            content: 'I don\'t fear death. I fear the act of dying without having accomplished my goals.',
            author: 'Thorfinn'
        }
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/33051/Mobile_Suit_Gundam__Iron-Blooded_Orphans_2nd_Season',
        name: 'Mobile Suit Gundam: IronBlooded Orphans',
        tags: ['Action', 'Mecha', 'Adventure', 'Psychological', 'Science Fiction'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/37520/Dororo',
        name: 'Dororo',
        tags: ['Action', 'Historical', 'Supernatural', 'Adventure', 'Psychological'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/31964/Boku_no_Hero_Academia?suggestion=',
        name: 'Boku No Hero Academia',
        tags: ['Comedy', 'Action', 'School', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'S+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/37999/Kaguyasama_wa_Kokurasetai__Tensaitachi_no_Renai_Zunousen',
        name: 'Kaguya sama wa Kokurasetai: Tensaitachi no Renai Zunousen',
        tags: ['Comedy', 'School', 'Romance'],
        quote: {
            content: 'How cute.',
            author: 'Kaguya Shinomiya'
        }
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/25099/Ore_ga_Ojousama_Gakkou_ni_Shomin_Sample_Toshite_Gets%E2%99%A5Sareta_Ken',
        name: 'Ore ga Ojousama Gakkou ni "Shomin Sample" Toshite Gets♥Sareta Ken',
        tags: ['Ecchi', 'Comedy', 'Harem', 'School', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/15315/Mondaijitachi_ga_Isekai_kara_Kuru_Sou_Desu_yo',
        name: 'Mondaiji tachi ga Isekai kara Kuru Sou Desu yo?',
        tags: ['Fantasy', 'Comedy', 'Isekai', 'Supernatural'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/32951/Rokudenashi_Majutsu_Koushi_to_Akashic_Records',
        name: 'Rokudenashi Majutsu Koushi to Akashic Records',
        tags: ['Comedy', 'Action', 'Harem', 'School', 'Fantasy', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/32901/Eromangasensei',
        name: 'Eromanga Sensei',
        tags: ['Comedy', 'Slice of Life', 'Ecchi', 'Harem', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/36632/Ore_ga_Suki_nano_wa_Imouto_dakedo_Imouto_ja_Nai',
        name: 'Ore ga Suki nano wa Imouto dakedo Imouto ja Nai',
        tags: ['Comedy', 'Slice of Life', 'Ecchi', 'Harem'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/37475/Kishuku_Gakkou_no_Juliet',
        name: 'Kishuku Gakkou no Juliet',
        tags: ['Comedy', 'Romance', 'School', 'Action'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/30296/Rakudai_Kishi_no_Cavalry',
        name: 'Rakudai Kishi no Cavalry',
        tags: ['Comedy', 'Action', 'Ecchi', 'School', 'Supernatural', 'Adventure', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35905/Ryuuou_no_Oshigoto',
        name: 'Ryuuou no Oshigoto!',
        tags: ['Comedy', 'Slice of Life', 'Game'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35507/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e_TV',
        name: 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e',
        tags: ['Comedy', 'Psychological', 'School', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/15809/Hataraku_Maou-sama',
        name: 'Hataraku Maou sama',
        tags: ['Comedy', 'Slice of Life', 'Fantasy', 'Supernatural', 'Romance'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/4898/Kuroshitsuji',
        name: 'Kuroshitsuji',
        tags: ['Supernatural', 'Action', 'Comedy', 'Historical', 'Fantasy'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/28171/Shokugeki_no_Souma',
        name: 'Shokugeki no Souma',
        tags: ['Food', 'Slice of Life', 'Ecchi', 'Comedy', 'School'],
        quote: {
            content: 'Do me a favour and stop deciding other people\'s happiness for them.',
            author: 'Soma Yukihira'
        }
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/20785/Mahouka_Koukou_no_Rettousei',
        name: 'Mahouka Koukou no Rettousei',
        tags: ['Action', 'Comedy', 'School', 'Science Fiction', 'Romance', 'Supernatural'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31637/Gate__Jieitai_Kanochi_nite_Kaku_Tatakaeri_Part_2',
        name: 'Gate: Jieitai Kanochi nite, Kaku Tatakaeri',
        tags: ['Military', 'Fantasy', 'Comedy', 'Harem', 'Action'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/34280/Gamers',
        name: 'Gamers!',
        tags: ['Comedy', 'Slice of Life', 'Game', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/38483/Ore_wo_Suki_nano_wa_Omae_dake_ka_yo',
        name: 'Ore wo Suki nano wa Omae dake ka yo',
        tags: ['Comedy', 'School', 'Romance', 'Harem'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/34443/Baki',
        name: 'Baki',
        tags: ['Action', 'Martial Art', 'Drama'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/29854/Ushio_to_Tora_TV',
        name: 'Ushio to Tora',
        tags: ['Action', 'Drama', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/40392/Runway_de_Waratte',
        name: 'Runway de Waratte',
        tags: ['Slice of Life', 'Psychological'],
    },
    {
        level: 'B+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/40046/Id_Invaded',
        name: 'Id:Invaded',
        tags: ['Action', 'Detective', 'Psychological', 'Science Fiction'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/38924/Nekopara',
        name: 'Nekopara ',
        tags: ['Comedy', 'Harem', 'Ecchi', 'Romance'],
    },
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/38476/Heya_Camp%E2%96%B3',
        name: 'Heya Camp△',
        tags: ['Slice of Life', 'Comedy', 'Sport'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/39196/Mairimashita_Iruma-kun',
        name: 'Mairimashita! Iruma kun',
        tags: ['Comedy', 'Fantasy', 'Supernatural', 'School', 'Isekai'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/39324/Uchi_no_Ko_no_Tame_naraba_Ore_wa_Moshikashitara_Maou_mo_Taoseru_kamo_Shirenai',
        name: 'Uchi no Ko no Tame naraba, Ore wa Moshikashitara Maou mo Taoseru kamo Shirenai',
        tags: ['Slice of Life', 'Fantasy'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/41226/Uzaki-chan_wa_Asobitai',
        name: 'Uzaki chan wa Asobitai!',
        tags: ['Slice of Life', 'Comedy', 'Ecchi'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/40056/Deca-Dence',
        name: 'Deca Dence',
        tags: ['Fantasy', 'Action', 'Science Fiction', 'Psychological'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/28121/Dungeon_ni_Deai_wo_Motomeru_no_wa_Machigatteiru_Darou_ka',
        name: 'Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka',
        tags: ['Fantasy', 'Action', 'Comedy', 'Adventure', 'Psychological'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/11111/Another',
        name: 'Another',
        tags: ['Horror', 'Supernatural', 'School'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/40571/Majo_no_Tabitabi',
        name: 'Majo no Tabitabi',
        tags: ['Adventure', 'Fantasy', 'Supernatural', 'Comedy'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/40748/Jujutsu_Kaisen_TV',
        name: 'Jujutsu Kaisen',
        tags: ['Action', 'Comedy', 'Supernatural', 'School', 'Horror'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/39017/Kyokou_Suiri',
        name: 'Kyokou Suiri',
        tags: ['Supernatural', 'Comedy', 'Detective', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31764/Nejimaki_Seirei_Senki__Tenkyou_no_Alderamin',
        name: 'Nejimaki Seirei Senki',
        tags: ['Action', 'Historical', 'Adventure', 'Military'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/41389/Tonikaku_Kawaii',
        name: 'Tonikaku Kawaii',
        tags: ['Romance', 'Comedy', 'Slice of Life'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/11843/Danshi_Koukousei_no_Nichijou',
        name: 'Danshi Koukousei no Nichijou',
        tags: ['School', 'Comedy', 'Slice of Life'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/39730/Houkago_Teibou_Nisshi',
        name: 'Houkago Teibou Nisshi',
        tags: ['School', 'Comedy', 'Slice of Life', 'Sport', 'Food'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31952/Kono_Bijutsubu_ni_wa_Mondai_ga_Aru',
        name: 'Kono Bijutsubu ni wa Mondai ga Aru!',
        tags: ['Comedy', 'School', 'Romance'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/34012/Isekai_Shokudou',
        name: 'Isekai Shokudou',
        tags: ['Food', 'Comedy', 'Slice of Life', 'Fantasy', 'Isekai', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/38787/Senryuu_Shoujo',
        name: 'Senryuu Shoujo',
        tags: ['Slice of Life', 'Comedy', 'School', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/37587/Lapis_Re_LiGHTs',
        name: 'Lapis Re:LiGHTs',
        tags: ['Music', 'Comedy', 'Fantasy', 'School'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/37806/Gunjou_no_Magmell',
        name: 'Gunjou no Magmell',
        tags: ['Action', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/38656/Darwins_Game',
        name: 'Darwin\'s Game',
        tags: ['Game', 'Action', 'Supernatural', 'Psychological'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/42897/Horimiya',
        name: 'Horimiya',
        tags: ['Slice of Life', 'Comedy', 'School', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31109/Hatsukoi_Monster',
        name: 'Hatsukoi Monster',
        tags: ['Comedy', 'School', 'Romance', 'Otome'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/34620/Kono_Yo_no_Hate_de_Koi_wo_Utau_Shoujo_YU-NO',
        name: 'Kono Yo no Hate de Koi wo Utau Shoujo YU NO',
        tags: ['Drama', 'Supernatural', 'Psychological', 'Fantasy'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/49160/Shachiku-san_wa_Youjo_Yuurei_ni_Iyasaretai',
        name: 'Shachiku san wa Youjo Yuurei ni Iyasaretai',
        tags: ['Slice of life', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/36754/Kakuriyo_no_Yadomeshi',
        name: 'Kakuriyo no Yadomeshi',
        tags: ['Fantasy', 'Comedy', 'Supernatural', 'Romance', 'Otome'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/43299/Wonder_Egg_Priority',
        name: 'Wonder Egg Priority',
        tags: ['Drama', 'Action', 'Comendy', 'Psychological', 'Supernatural'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/41392/Urasekai_Picnic',
        name: 'Urasekai Picnic',
        tags: ['Fantasy', 'Action', 'Adventure', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/43692/Gokushufudou',
        name: 'Gokushufudou',
        tags: ['Slice of Life', 'Comedy'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://www.imdb.com/title/tt14069590/',
        name: 'DOTA: Dragon\'s Blood',
        tags: ['Fantasy', 'Action', 'Adventure', 'Supernatural'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/37171/Asobi_Asobase',
        name: 'Asobi Asobase',
        tags: ['Comedy', 'School'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/21327/Isshuukan_Friends',
        name: 'Isshuukan Friends',
        tags: ['Slice of Life', 'Comedy', 'School', 'Psychological'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/39326/Kawaikereba_Hentai_demo_Suki_ni_Natte_Kuremasu_ka',
        name: 'Kawaikereba Hentai demo Suki ni Natte Kuremasu ka?',
        tags: ['Ecchi', 'Comedy', 'Harem', 'School', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/40685/Super_Cub',
        name: 'Super Cub',
        tags: ['Slice of Life', 'School'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/41457/86',
        name: '86',
        tags: ['Action', 'Mecha', 'Drama', 'Adventure', 'Science Fiction', 'Psychological'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/46095/Vivy__Fluorite_Eyes_Song',
        name: 'Vivy: Fluorite Eye\'s Song',
        tags: ['Action', 'Science Fiction', 'Psychological'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/42249/Tokyo_Revengers',
        name: 'Tokyo Revengers',
        tags: ['Action', 'Drama', 'School', 'Supernatural'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/40911/Yuukoku_no_Moriarty',
        name: 'Yuukoku no Moriarty',
        tags: ['Historical', 'Psychological', 'Action', 'Detective'],
    },
    {
        level: 'S',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35484/Osake_wa_Fuufu_ni_Natte_kara',
        name: 'Osake wa Fuufu ni Natte kara',
        tags: ['Slice of Life', 'Comedy', 'Romance', 'Otome'],
        quote: {
            content: 'If you hug someone for thirty seconds, feel better, supposedly.',
            author: 'Sora Mizusawa'
        }
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/35413/Imouto_sae_Ireba_Ii',
        name: 'Imouto sae Ireba Ii',
        tags: ['Comedy', 'Slice of Life', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/44942/Shuumatsu_no_Walk%C3%BCre',
        name: 'Shuumatsu No Valkyrie',
        tags: ['Action', 'Drama', 'Martial Art'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33731/Gabriel_DropOut',
        name: 'Gabriel DropOut',
        tags: ['Comedy', 'School', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/17549/Non_Non_Biyori',
        name: 'Non Non Biyori',
        tags: ['Slice of Life', 'Comedy', 'School'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/40904/Bokutachi_no_Remake',
        name: 'Bokutachi no Remake',
        tags: ['Slice of Life', 'Comedy', 'School', 'Psychological', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/46093/Shiroi_Suna_no_Aquatope',
        name: 'Shiroi Suna no Aquatope',
        tags: ['Slice of Life', 'Comedy', 'Psychological'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/47257/Shinigami_Bocchan_to_Kuro_Maid',
        name: 'Shinigami Bocchan to Kuro Maid',
        tags: ['Comedy', 'Romance', 'Drama', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/23283/Zankyou_no_Terror',
        name: 'Zankyou no Terror',
        tags: ['Action', 'Psychological'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/48753/Jahy-sama_wa_Kujikenai',
        name: 'Jahy sama wa Kujikenai!',
        tags: ['Comedy', 'Supernatural'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/32281/Kimi_no_Na_wa',
        name: 'Kimi no Na wa',
        tags: ['Romance', 'Slice of Life', 'Psychological', 'Supernatural', 'Comedy'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/38826/Tenki_no_Ko',
        name: 'Tenki no Ko',
        tags: ['Romance', 'Slice of Life', 'Supernatural', 'Comedy'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/40787/Josee_to_Tora_to_Sakana-tachi',
        name: 'Josee to Tora to Sakana tachi',
        tags: ['Romance', 'Slice of Life', 'Comedy', 'Drama'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/199/Sen_to_Chihiro_no_Kamikakushi',
        name: 'Sen to Chihiro no Kamikakushi',
        tags: ['Psychological', 'Supernatural', 'Fantasy', 'Romance'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/523/Tonari_no_Totoro',
        name: 'Tonari no Totoro',
        tags: ['Supernatural', 'Psychological'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/34498/Uchiage_Hanabi_Shita_kara_Miru_ka_Yoko_kara_Miru_ka',
        name: 'Uchiage Hanabi, Shita kara Miru ka? Yoko kara Miru ka?',
        tags: ['Romance', 'School', 'Drama', 'Supernatural'],
    },
    {
        level: 'A',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/1689/Byousoku_5_Centimeter',
        name: 'Byousoku 5 Centimeter',
        tags: ['Romance', 'Psychological', 'Drama'],
    },
    {
        level: 'B+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/9760/Hoshi_wo_Ou_Kodomo',
        name: 'Hoshi wo Ou Kodomo',
        tags: ['Adventure', 'Supernatural', 'Drama', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/36098/Kimi_no_Suizou_wo_Tabetai',
        name: 'Kimi no Suizou wo Tabetai',
        tags: ['Psychological', 'Slice of Life', 'Romance', 'Drama'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/28851/Koe_no_Katachi',
        name: 'Koe no Katachi',
        tags: ['Psychological', 'Slice of Life', 'Romance', 'Drama', 'School'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/28725/Kokoro_ga_Sakebitagatterunda',
        name: 'Kokoro ga Sakebitagatterunda',
        tags: ['Psychological', 'School', 'Romance', 'Drama'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/10408/Hotarubi_no_Mori_e',
        name: 'Hotarubi no Mori e',
        tags: ['Supernatural', 'Romance'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/16782/Kotonoha_no_Niwa',
        name: 'Kotonoha no Niwa',
        tags: ['Drama', 'Slice of Life', 'Romance'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/16417/Tamako_Market',
        name: 'Tamako Market',
        tags: ['School', 'Slice of Life', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/23277/Saenai_Heroine_no_Sodatekata',
        name: 'Saenai Heroine no Sodatekata',
        tags: ['Comedy', 'Harem', 'Slice of Life', 'Romance'],
        quote: {
            content: 'They\'re human beings who are more appealing that real girls with warm blood flowing through their veins! That\'s what you have to be!',
            author: 'Tomoya Aki'
        }
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/25013/Akatsuki_no_Yona',
        name: 'Akatsuki no Yona',
        tags: ['Comedy', 'Action', 'Historical', 'Adventure', 'Martial Art', 'Supernatural', 'Romance', 'Otome'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/26243/Owari_no_Seraph',
        name: 'Owari no Seraph',
        tags: ['Action', 'Fantasy', 'Psychological', 'Drama'],
    },
    {
        level: 'S+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/16662/Kaze_Tachinu',
        name: 'Kaze Tachinu',
        tags: ['Historical', 'Romance'],
        quote: {
            content: 'Le vent se lève! . . . Il faut tenter de vivre!',
            author: 'Jirou Horikoshi'
        }
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/40716/Kakushigoto_TV',
        name: 'Kakushigoto ',
        tags: ['Slice of Life', 'Comedy'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/36108/Takunomi',
        name: 'Takunomi',
        tags: ['Slice of Life', 'Comedy'],
    },
    {
        level: 'S-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/34599/Made_in_Abyss',
        name: 'Made in Abyss',
        tags: ['Fantasy', 'Adventure', 'Action', 'Mecha', 'Supernatural', 'Science Fiction', 'Psychological', 'Horror'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/34102/Sakurada_Reset',
        name: 'Sakurada Reset',
        tags: ['Supernatural', 'Psychological', 'School'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/48471/Tsuki_to_Laika_to_Nosferatu',
        name: 'Tsuki to Laika to Nosferatu',
        tags: ['Drama', 'Historical', 'Romance', 'Fantasy'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/46352/Blue_Period',
        name: 'Blue Period',
        tags: ['Drama', 'Slice of Life', 'School', 'Psychological'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/41833/Kyuuketsuki_Sugu_Shinu',
        name: 'Kyuuketsuki Sugu Shinu',
        tags: ['Comedy', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/45055/Taishou_Otome_Otogibanashi',
        name: 'Taishou Otome Otogibanashi',
        tags: ['Slice of Life', 'Comedy', 'Romance', 'Historical', 'Psychological'],
    },
    {
        level: 'A+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/48926/Komi-san_wa_Comyushou_desu',
        name: 'Komi san wa, Comyushou desu',
        tags: ['Slice of Life', 'Comedy', 'School'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/42351/Senpai_ga_Uzai_Kouhai_no_Hanashi',
        name: 'Senpai ga Uzai Kouhai no Hanashi',
        tags: ['Slice of Life', 'Comedy', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/20541/Mikakunin_de_Shinkoukei',
        name: 'Mikakunin de Shinkoukei',
        tags: ['Slice of Life', 'Comedy', 'School', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/36793/3D_Kanojo__Real_Girl',
        name: '3D Kanojo: Real Girl',
        tags: ['School', 'Romance'],
    },
    {
        level: 'S-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/41025/Fumetsu_no_Anata_e',
        name: 'Fumetsu no Anata e',
        tags: ['Adventure', 'Psychological', 'Supernatural', 'Drama', 'Action'],
        quote: {
            content: 'I\'m sure some of it will be bad, but I still want to learn about the world.',
            author: 'Fushi'
        }
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/11499/Sankarea',
        name: 'Sankarea',
        tags: ['Drama', 'Comedy', 'Supernatural', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/431/Howl_no_Ugoku_Shiro',
        name: 'Howl no Ugoku Shiro',
        tags: ['Drama', 'Fantasy', 'Adventure', 'Supernatural', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/30187/Sakurako-san_no_Ashimoto_ni_wa_Shitai_ga_Umatteiru',
        name: 'Sakurako san no Ashimoto ni wa Shitai ga Umatteiru',
        tags: ['Drama', 'Detective'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/12355/Ookami_Kodomo_no_Ame_to_Yuki',
        name: 'Ookami Kodomo no Ame to Yuki',
        tags: ['Slice of Life', 'Psychological', 'Supernatural', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/486/Kino_no_Tabi__The_Beautiful_World',
        name: 'Kino no Tabi: The Beautiful World',
        tags: ['Slice of Life', 'Adventure'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/11013/Inu_x_Boku_SS',
        name: 'Inu x Boku SS',
        tags: ['Comedy', 'Supernatural', 'Romance'],
    },
    {
        level: 'S',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35120/Devilman__Crybaby',
        name: 'Devilman series',
        tags: ['Fantasy', 'Action', 'Horror', 'Supernatural', 'Psychological'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/45425/Slow_Loop',
        name: 'Slow Loop',
        tags: ['Comedy', 'Slice of Life', 'Sport'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/48736/Sono_Bisque_Doll_wa_Koi_wo_Suru',
        name: 'Sono Bisque Doll wa Koi wo Suru',
        tags: ['Comedy', 'Slice of Life', 'Romance'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/48553/Akebi-chan_no_Sailor-fuku',
        name: 'Akebi chan no Sailor fuku',
        tags: ['Comedy', 'Slice of Life', 'School'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/44961/Platinum_End',
        name: 'Platinum End',
        tags: ['Psychological', 'Drama', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/48414/Sabikui_Bisco',
        name: 'Sabikui Bisco',
        tags: ['Adventure', 'Action', 'Fantasy'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/48997/Fantasy_Bishoujo_Juniku_Ojisan_to',
        name: 'Fantasy Bishoujo Juniku Ojisan to',
        tags: ['Adventure', 'Action', 'Fantasy', 'Isekai', 'Comedy'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/30014/Momokuri',
        name: 'Momokuri',
        tags: ['Slice of Life', 'Comedy', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/48580/Vanitas_no_Karte',
        name: 'Vanitas no Karte',
        tags: ['Fantasy', 'Action', 'Historical', 'Comedy', 'Supernatural', 'Adventure', 'Romance', 'Drama'],
    },
    {
        level: 'S+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/12431/Uchuu_Kyoudai',
        name: 'Uchuu Kyoudai',
        tags: ['Slice of Life', 'Comedy', 'Science Fiction', 'Psychological'],
        quote: {
            content: 'Some things can\'t be prevented. The last of which, is death. All we can do is live until the day we die. Control what we can… and fly free!',
            author: 'Deniel Young'
        }
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33206/Kobayashi-san_Chi_no_Maid_Dragon',
        name: 'Kobayashi san Chi no Maid Dragon',
        tags: ['Comedy', 'Slice of Life', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35968/Wotaku_ni_Koi_wa_Muzukashii',
        name: 'Wotaku ni Koi wa Muzukashii',
        tags: ['Comedy', 'Slice of Life', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/23273/Shigatsu_wa_Kimi_no_Uso',
        name: 'Shigatsu wa Kimi no Uso',
        tags: ['Music', 'Psychological', 'Slice of Life', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/30016/Nanbaka',
        name: 'Nanbaka',
        tags: ['Comedy', 'Action', 'Supernatural', 'Drama'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/42893/The_God_of_Highschool',
        name: 'The God of Highschool',
        tags: ['Action', 'Martial Art', 'Supernatural', 'Drama', 'Comedy'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/28825/Himouto_Umaru-chan',
        name: 'Himouto! Umaru chan',
        tags: ['Comedy', 'Slice of Life', 'School'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/41168/Nakitai_Watashi_wa_Neko_wo_Kaburu',
        name: 'Nakitai Watashi wa Neko wo Kaburu',
        tags: ['Drama', 'Supernatural', 'Romance'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/17265/Log_Horizon',
        name: 'Log Horizon',
        tags: ['Game', 'Fantasy', 'Adventure', 'Action', 'Isekai', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/10495/Yuru_Yuri',
        name: 'Yuru Yuri',
        tags: ['Comedy', 'School', 'Slice of Life'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/10161/No6',
        name: 'No.6',
        tags: ['Action', 'Drama', 'Supernatural', 'Science Fiction'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/16706/Kami_nomi_zo_Shiru_Sekai__Megami-hen',
        name: 'Kami nomi zo Shiru Sekai: Megami hen',
        tags: ['Game', 'Comedy', 'Harem', 'Supernatural', 'Romance'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/15225/Hentai_Ouji_to_Warawanai_Neko',
        name: 'Hentai Ouji to Warawanai Neko',
        tags: ['Comedy', 'Slice of Life', 'Supernatural', 'Romance'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/16009/Kamisama_no_Inai_Nichiyoubi',
        name: 'Kamisama no Inai Nichiyoubi',
        tags: ['Psychological', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'A-',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/16067/Nagi_no_Asu_kara',
        name: 'Nagi no Asu kara',
        tags: ['Fantasy', 'Comedy', 'School'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/32438/Mayoiga',
        name: 'Mayoiga',
        tags: ['Fantasy', 'Comedy', 'School'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31804/Kuma_Miko',
        name: 'Kuma Miko',
        tags: ['Slice of Life', 'Comedy', 'Supernatural'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/33337/ACCA__13-ku_Kansatsu-ka',
        name: 'ACCA: 13 ku Kansatsu ka',
        tags: ['Drama', 'Detective', 'Historical'],
    },
    {
        level: 'A+',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/35838/Shoujo_Shuumatsu_Ryokou',
        name: 'Shoujo Shuumatsu Ryokou',
        tags: ['Adventure', 'Fantasy', 'Slice of Life'],
    },
    {
        level: 'B-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/36220/Itsudatte_Bokura_no_Koi_wa_10_cm_Datta',
        name: 'Itsudatte Bokura no Koi wa 10 cm Datta',
        tags: ['Comedy', 'School', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/36124/Itou_Junji__Collection',
        name: 'Itou Junji: Collection',
        tags: ['Horror', 'Psychological', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/35889/Hakata_Tonkotsu_Ramens',
        name: 'Hakata Tonkotsu Ramens',
        tags: ['Action', 'Psychological'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/37779/Yakusoku_no_Neverland',
        name: 'Yakusoku no Neverland',
        tags: ['Drama', 'Psychological', 'Adventure', 'Fantasy', 'Horror', 'Action'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/39534/Jibaku_Shounen_Hanako-kun',
        name: 'Jibaku Shounen Hanako kun',
        tags: ['Comedy', 'School', 'Supernatural', 'Otome'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/39575/Somali_to_Mori_no_Kamisama',
        name: 'Somali to Mori no Kamisama',
        tags: ['Adventure', 'Slice of Life', 'Fantasy'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/48858/180_Byou_de_Kimi_no_Mimi_wo_Shiawase_ni_Dekiru_ka',
        name: '180 Byou de Kimi no Mimi wo Shiawase ni Dekiru ka?',
        tags: ['Slice of Life'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/44516/Koroshi_Ai',
        name: 'Koroshi Ai',
        tags: ['Action', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/35672/Yama_no_Susume_Third_Season',
        name: 'Yama no Susume',
        tags: ['Comedy', 'Sport', 'Slice of Life'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/50549/Bubble',
        name: 'Bubble',
        tags: ['Supernatural', 'Sport', 'Romance', 'Adventure', 'Comedy'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/9989/Ano_Hi_Mita_Hana_no_Namae_wo_Bokutachi_wa_Mada_Shiranai',
        name: 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai',
        tags: ['Slice of Life', 'Supernatural'],
    },
    {
        level: 'S-',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/50380/Paripi_Koumei',
        name: 'Paripi Koumei',
        tags: ['Music', 'Comedy', 'Isekai'],
        quote: {
            content: 'If you bow to emotion, you invite disaster.',
            author: 'Koumei'
        }
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/50265/Spy_x_Family',
        name: 'Spy x Family',
        tags: ['Comedy', 'Action', 'School', 'Supernatural'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/47194/Summertime_Render',
        name: 'Summertime Render',
        tags: ['Detective', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/48779/Deaimon',
        name: 'Deaimon',
        tags: ['Slice of Life'],
    },
    {
        level: 'A',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/50273/Tomodachi_Game',
        name: 'Tomodachi Game',
        tags: ['Psychological', 'Game'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/457/Mushishi',
        name: 'Mushishi',
        tags: ['Supernatural', 'Adventure'],
        quote: {
            content: 'If you throw your life away, you won\'t even have the capacity to feel regret.',
            author: 'Ginko'
        }
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/manga/116157/Otome_Game_Sekai_wa_Mob_ni_Kibishii_Sekai_desu',
        name: 'Otome Game Sekai wa Mob ni Kibishii Sekai desu',
        tags: ['Fantasy', 'Isekai', 'Harem', 'Action', 'Mecha'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/49520/Aharen-san_wa_Hakarenai',
        name: 'Aharen san wa Hakarenai',
        tags: ['School', 'Comedy', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/43439/Shadows_House',
        name: 'Shadows House',
        tags: ['Drama', 'Fantasy', 'Supernatural', 'Psychological'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/36028/Golden_Kamuy',
        name: 'Golden Kamuy',
        tags: ['Action', 'Adventure', 'Historical', 'Military', 'Drama'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/37614/Hitoribocchi_no_Marumaru_Seikatsu',
        name: 'Hitoribocchi no Marumaru Seikatsu',
        tags: ['School', 'Comedy', 'Slice of Life'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/28497/Rokka_no_Yuusha',
        name: 'Rokka no Yuusha',
        tags: ['Fantasy', 'Action', 'Drama', 'Detective'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/1210/NHK_ni_Youkoso',
        name: 'NHK ni Youkoso!',
        tags: ['Psychological', 'Comedy', 'Slice of Life', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33726/Saiyuuki_Reload_Blast',
        name: 'Saiyuuki Reload Blast',
        tags: ['Fantasy', 'Adventure', 'Action', 'Supernatural', 'Comedy'],
    },
    {
        level: 'S-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/31646/3-gatsu_no_Lion',
        name: '3-gatsu no Lion',
        tags: ['Psychological', 'Slice of Life'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/40834/Ousama_Ranking',
        name: 'Ousama Ranking',
        tags: ['Fantasy', 'Adventure', 'Action', 'Supernatural', 'Comedy'],
    },
    {
        level: 'B-',
        imgP: 'bottom',
        link: 'https://myanimelist.net/anime/49665/Blue_Thermal',
        name: 'Blue Thermal',
        tags: ['Drama', 'Otome'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/50346/Yofukashi_no_Uta',
        name: 'Yofukashi no Uta',
        tags: ['Comedy', 'Supernatural', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/45653/Soredemo_Ayumu_wa_Yosetekuru',
        name: 'Soredemo Ayumu wa Yosetekuru',
        tags: ['Comedy', 'School', 'Romance'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/42310/Cyberpunk__Edgerunners',
        name: 'Cyberpunk: Edgerunners',
        tags: ['Action', 'Science Fiction', 'Romance'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/50709/Lycoris_Recoil',
        name: 'Lycoris Recoil',
        tags: ['Action', 'Comedy'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/49938/Ame_wo_Tsugeru_Hyouryuu_Danchi',
        name: 'Ame wo Tsugeru Hyouryuu Danchi',
        tags: ['Supernatural', 'Adventure', 'Drama'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/38015/Shika_no_Ou__Yuna_to_Yakusoku_no_Tabi',
        name: 'Shika no Ou: Yuna to Yakusoku no Tabi',
        tags: ['Fantasy', 'Supernatural', 'Adventure', 'Action'],
    },
    {
        level: 'S',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/47917/Bocchi_the_Rock',
        name: 'Bocchi the Rock!',
        tags: ['Comedy', 'Music', 'Slice of Life', 'School'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/44511/Chainsaw_Man',
        name: 'Chainsaw Man',
        tags: ['Action', 'Supernatural', 'Horror'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/50205/Arknights__Reimei_Zensou',
        name: 'Arknights: Reimei Zensou',
        tags: ['Fantasy', 'Action', 'Supernatural', 'Adventure'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/49828/Kidou_Senshi_Gundam__Suisei_no_Majo',
        name: 'Kidou Senshi Gundam: Suisei no Majo',
        tags: ['Gundam', 'Action', 'Science Fiction'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/48316/Kage_no_Jitsuryokusha_ni_Naritakute',
        name: 'Kage no Jitsuryokusha ni Naritakute!',
        tags: ['Fantasy', 'Comedy', 'Action', 'Isekai'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/10162/Usagi_Drop/',
        name: 'Usagi Drop',
        tags: ['Slice of Life'],
    },
    {
        level: 'S',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/50739/Otonari_no_Tenshi-sama_ni_Itsunomanika_Dame_Ningen_ni_Sareteita_Ken',
        name: 'Otonari no Tenshi-sama ni Itsunomanika Dame Ningen ni Sareteita Ken',
        tags: ['Romance', 'Slice of Life', 'School'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52173/Koori_Zokusei_Danshi_to_Cool_na_Douryou_Joshi',
        name: 'Koori Zokusei Danshi to Cool na Douryou Joshi',
        tags: ['Romance', 'Slice of Life'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/49835/Kimi_wo_Aishita_Hitori_no_Boku_e',
        name: 'Kimi wo Aishita Hitori no Boku e',
        tags: ['Science Fiction', 'Romance', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/597/Neko_no_Ongaeshi',
        name: 'Neko no Ongaeshi',
        tags: ['Adventure', 'Supernatural'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/585/Mimi_wo_Sumaseba',
        name: 'Mimi wo Sumaseba',
        tags: ['Slice of Life', 'Romance'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/52736/Tensei_Oujo_to_Tensai_Reijou_no_Mahou_Kakumei',
        name: 'Tensei Oujo to Tensai Reijou no Mahou Kakumei',
        tags: ['Fantasy', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/52305/Tomo-chan_wa_Onnanoko',
        name: 'Tomo-chan wa Onnanoko!',
        tags: ['Comedy', 'School', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/339/Serial_Experiments_Lain',
        name: 'Serial Experiments Lain',
        tags: ['Psychological', 'Science Fiction'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/51116/Kagami_no_Kojou',
        name: 'Kagami no Kojou',
        tags: ['Supernatural', 'Drama'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/50416/Skip_to_Loafer',
        name: 'Skip to Loafer',
        tags: ['School', 'Slice of Life', 'Romance', 'Drama'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/51815/Kubo-san_wa_Mob_wo_Yurusanai',
        name: 'Kubo-san wa Mob wo Yurusanai',
        tags: ['School', 'Slice of Life', 'Romance'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/53126/Yamada-kun_to_Lv999_no_Koi_wo_Suru',
        name: 'Yamada-kun to Lv999 no Koi wo Suru',
        tags: ['Slice of Life', 'Romance', 'Comedy'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/53393/Tengoku_Daimakyou',
        name: 'Tengoku Daimakyou',
        tags: ['Adventure', 'Supernatural', 'Drama'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/50248/Birdie_Wing__Golf_Girls_Story',
        name: 'Birdie Wing: Golf Girls\' Story',
        tags: ['Sport', 'Drama'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/52081/Edomae_Elf',
        name: 'Edomae Elf',
        tags: ['Comedy', 'Slice of Life', 'Supernatural'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/53613/Dead_Mount_Death_Play',
        name: 'Dead Mount Death Play',
        tags: ['Supernatural', 'Action', 'Fantasy'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/52308/Kanojo_ga_Koushaku-tei_ni_Itta_Riyuu',
        name: 'Kanojo ga Koushaku-tei ni Itta Riyuu',
        tags: ['Otome', 'Romance', 'Drama', 'Fantasy'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/50796/Kimi_wa_Houkago_Insomnia',
        name: 'Kimi wa Houkago Insomnia',
        tags: ['Romance', 'Slice of Life', 'School'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/50594/Suzume_no_Tojimari',
        name: 'Suzume no Tojimari',
        tags: ['Supernatural', 'Romance', 'Adventure'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/46569/Jigokuraku',
        name: 'Jigokuraku',
        tags: ['Fantasy', 'Supernatural', 'Adventure', 'Action', 'Historical'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/53434/Maou_no_Ore_ga_Dorei_Elf_wo_Yome_ni_Shitanda_ga_Dou_Medereba_Ii',
        name: 'Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?',
        tags: ['Supernatural', 'Romance', 'Comedy', 'Fantasy'],
    },
    {
        level: 'A-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/52034/Oshi_no_Ko',
        name: 'Oshi no Ko',
        tags: ['Drama', 'Music', 'Romance', 'Psychological'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52034/Oshi_no_Ko',
        name: 'Lv1 Maou to One Room Yuusha',
        tags: ['Comedy', 'Fantasy', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'top',
        link: 'https://myanimelist.net/manga/106937/Ao_no_Orchestra',
        name: 'Ao no Orchestra',
        tags: ['Drama', 'Music', 'School'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52505/Dark_Gathering',
        name: 'Dark Gathering',
        tags: ['Horror', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/53379/Uchi_no_Kaisha_no_Chiisai_Senpai_no_Hanashi',
        name: 'Uchi no Kaisha no Chiisai Senpai no Hanashi',
        tags: ['Comedy', 'Romance'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/50613/Rurouni_Kenshin__Meiji_Kenkaku_Romantan_2023',
        name: 'Rurouni Kenshin: Meiji Kenkaku Romantan',
        tags: ['Historical', 'Otome', 'Action', 'Romance'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/50582/Nanatsu_no_Maken_ga_Shihai_suru',
        name: 'Nanatsu no Maken ga Shihai suru',
        tags: ['Fantasy', 'Supernatural', 'School', 'Action'],
    },
    {
        level: 'A-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/53787/AI_no_Idenshi',
        name: 'AI no Idenshi',
        tags: ['Science Fiction', 'Drama'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/54790/Undead_Girl_Murder_Farce',
        name: 'Undead Girl Murder Farce',
        tags: ['Supernatural', 'Action', 'Adventure', 'Detective', 'Historical'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/54112/Zom_100__Zombie_ni_Naru_made_ni_Shitai_100_no_Koto/characters',
        name: 'Zom 100: Zombie ni Naru made ni Shitai 100 no Koto',
        tags: ['Comedy', 'Supernatural', 'Action', 'Adventure'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/51552/Watashi_no_Shiawase_na_Kekkon',
        name: 'Watashi no Shiawase na Kekkon',
        tags: ['Romance', 'Otome', 'Supernatural', 'Drama', 'Historical'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/51105/NieR_Automata_Ver11a',
        name: 'NieR:Automata Ver1.1a',
        tags: ['Science Friction', 'Fantasy', 'Action', 'Adventure'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/33/Kenpuu_Denki_Berserk/',
        name: 'Berserk',
        tags: ['Action', 'Adventure', 'Military', 'Horror', 'Historical', 'Fantasy', 'Supernatural', 'Drama', 'Romance'],
    },
    {
        level: 'B+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/52934/Konyaku_Haki_sareta_Reijou_wo_Hirotta_Ore_ga_Ikenai_Koto_wo_Oshiekomu',
        name: 'Konyaku Haki sareta Reijou wo Hirotta Ore ga, Ikenai Koto wo Oshiekomu',
        tags: ['Comedy', 'Romance', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52985/Dekoboko_Majo_no_Oyako_Jijou',
        name: 'Dekoboko Majo no Oyako Jijou',
        tags: ['Comedy', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/31043/Boku_dake_ga_Inai_Machi',
        name: 'Boku dake ga Inai Machi',
        tags: ['Drama', 'Detective', 'Supernatural'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52991/Sousou_no_Frieren',
        name: 'Sousou no Frieren',
        tags: ['Adventure', 'Fantasy', 'Slice of Life', 'Supernatural', 'Drama'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/32998/91_Days',
        name: '91 Days',
        tags: ['Action', 'Drama', 'Detective', 'Historical'],
    },
    {
        level: 'A',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/52701/Dungeon_Meshi',
        name: 'Dungeon Meshi',
        tags: ['Food', 'Fantasy', 'Supernatural'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52816/Majo_to_Yajuu',
        name: 'Majo to Yajuu',
        tags: ['Action', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/53026/Synduality__Noir',
        name: 'Synduality: Noir',
        tags: ['Mecha', 'Action', 'Science Fiction', 'Fantasy', 'Drama'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/53421/Dosanko_Gal_wa_Namara_Menkoi',
        name: 'Dosanko Gal wa Namara Menkoi',
        tags: ['Slice of Life', 'School', 'Comedy', 'Romance', 'Harem'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/56285/Ninja_Kamui',
        name: 'Ninja Kamui',
        tags: ['Action', 'Science Fiction', 'Martial Art'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/55774/Himesama_Goumon_no_Jikan_desu',
        name: 'Himesama "Goumon" no Jikan desu',
        tags: ['Comedy', 'Fantasy'],
    },
    {
        level: 'B-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/56352/Loop_7-kaime_no_Akuyaku_Reijou_wa_Moto_Tekikoku_de_Jiyuu_Kimama_na_Hanayome_Seikatsu_wo_Mankitsu_suru',
        name: 'Loop 7-kaime no Akuyaku Reijou wa, Moto Tekikoku de Jiyuu Kimama na Hanayome Seikatsu wo Mankitsu suru',
        tags: ['Drama', 'Romance', 'Otome', 'Historical'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/55866/Yubisaki_to_Renren',
        name: 'Yubisaki to Renren',
        tags: ['Romance', 'Otome', 'Slice of Life', 'Drama'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52741/Undead_Unluck',
        name: 'Undead Unluck',
        tags: ['Action', 'Supernatural', 'Romance'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52211/Mashle',
        name: 'Mashle',
        tags: ['Comedy', 'Action', 'Supernatural', 'Fantasy'],
    },
    {
        level: 'B+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52299/Ore_dake_Level_Up_na_Ken?cat=anime',
        name: 'Solo Leveling',
        tags: ['Action', 'Supernatural', 'Drama'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/22535/kiseijuu__sei_no_kakuritsu',
        name: 'Kiseijuu: Sei no Kakuritsu',
        tags: ['Action', 'Supernatural', 'Horror', 'Psychological', 'Drama'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/39489/Spriggan_ONA',
        name: 'Spriggan',
        tags: ['Action', 'Supernatural', 'Adventure', 'Science Fiction'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/31580/Ajin',
        name: 'Ajin',
        tags: ['Action', 'Supernatural', 'Horror', 'Detective'],
        quote: {
            content: 'A winning hand\'s only good when you keep your cards hidden.',
            author: 'Kei Nagai'
        }
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/47/Akira?cat=anime',
        name: 'Akira',
        tags: ['Action', 'Supernatural', 'Science Fiction', 'Drama'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/52588/Kaijuu_8-gou',
        name: 'Kaijuu 8-gou',
        tags: ['Action', 'Supernatural', 'Science Fiction', 'Comedy'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/53407/Bartender__Kami_no_Glass',
        name: 'Bartender: Kami no Glass',
        tags: ['Slice of Life', 'Food'],
    },
    {
        level: 'S',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/54839/Yoru_no_Kurage_wa_Oyogenai',
        name: 'Yoru no Kurage wa Oyogenai',
        tags: ['Slice of Life', 'Music', 'Psychological', 'Drama'],
    },
    {
        level: 'A+',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/56230/Jiisan_Baasan_Wakagaeru',
        name: 'Jiisan Baasan Wakagaeru',
        tags: ['Slice of Life', 'Romance', 'Comedy'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/57217/Katsute_Mahou_Shoujo_to_Aku_wa_Tekitai_shiteita',
        name: 'Katsute Mahou Shoujo to Aku wa Tekitai shiteita',
        tags: ['Romance', 'Comedy', 'Supernatural'],
    },
    {
        level: 'B',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/56348/Dungeon_no_Naka_no_Hito',
        name: 'Dungeon no Naka no Hito',
        tags: ['Fantasy', 'Comedy', 'Supernatural'],
    },
    {
        level: 'S-',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/54284/VTuber_Nandaga_Haishin_Kiri_Wasuretara_Densetsu_ni_Natteta',
        name: 'VTuber Nandaga Haishin Kiri Wasuretara Densetsu ni Natteta',
        tags: ['Comedy', 'Game'],
    },
    {
        level: 'S-',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/54968/Giji_Harem',
        name: 'Giji Harem',
        tags: ['Comedy', 'Romance', 'School'],
    },
    {
        level: 'A',
        imgP: 'center',
        link: 'https://myanimelist.net/anime/58426/Shikanoko_Nokonoko_Koshitantan',
        name: 'Shikanoko Nokonoko Koshitantan',
        tags: ['Comedy'],
    },
    {
        level: 'A+',
        imgP: 'top',
        link: 'https://myanimelist.net/anime/53128/Atri__My_Dear_Moments',
        name: 'Atri: My Dear Moments',
        tags: ['Comedy', 'Romance', 'Science Fiction', 'Drama'],
        quote: {
            content: 'Stop, moment, you are beautiful',
        }
    },
]

export default animeList